@@include('app.js', {})
@@include('sliders.js', {})
@@include('showPassword.js', {})
@@include('agreeDeleteModal.js',{})
@@include('stepForm.js',{})
@@include('checkPassword.js',{})
@@include('radio-tabs.js',{})
@@include('phone-mask.js',{})
